_RGBM_SINGLE_DYNAMIC(HEATMAP)
_RGBM_SINGLE_DYNAMIC(ICEWAVE)
_RGBM_SINGLE_DYNAMIC(STATIC)
_RGBM_SINGLE_DYNAMIC(MOUSEMOVE)
_RGBM_SINGLE_DYNAMIC(SCROLLMOVE)

#undef _RGBM_SINGLE_STATIC
#undef _RGBM_SINGLE_DYNAMIC
#undef _RGBM_MULTI_STATIC
#undef _RGBM_MULTI_DYNAMIC
#undef _RGBM_TMP_STATIC
#undef _RGBM_TMP_DYNAMIC
