#pragma once

#include "../../config.h"

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define VIAL_KEYBOARD_UID {0x80, 0x42, 0x18, 0x02, 0xE7, 0xBD, 0xAB, 0x0C}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#ifndef VIA_FIRMWARE_VERSION
#define VIA_FIRMWARE_VERSION 0x00010000
#endif

#undef VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT
#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0
