name: Keyball manual build

on:
  workflow_dispatch:
    inputs:
      kb:
        description: "Keyboard (例: keyball/keyball44, keyball/keyball39)"
        required: true
        default: "keyball/keyball44"
      km:
        description: "Keymap"
        required: true
        default: "mymap"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.kb }}-${{ inputs.km }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ inputs.kb }}:${{ inputs.km }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive         # qmk_firmware サブモジュールも取得
          ref: ${{ github.ref }}        # UIで選んだブランチのHEAD

      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi python3-venv

      - name: Setup qmk (venv)
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install -U pip qmk
          qmk setup -H "$GITHUB_WORKSPACE/qmk_firmware" -y || true

      - name: Link keyboards/keyball → ../../keyball
        run: |
          rm -rf qmk_firmware/keyboards/keyball
          mkdir -p qmk_firmware/keyboards
          ln -s ../../keyball qmk_firmware/keyboards/keyball

      - name: Build
        run: |
          . .venv/bin/activate
          qmk clean -q -n -y || true
          qmk compile -kb "${{ inputs.kb }}" -km "${{ inputs.km }}"

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.kb }}-${{ inputs.km }}
          path: qmk_firmware/.build/*

